In [1]:
import bdpy 

data = bdpy.BData('./Subject1.h5')


In [2]:
data

In [5]:
data.show_metadata()

| Key            | Description                                                                       |
|----------------|-----------------------------------------------------------------------------------|
| DataType       | 1 = Data type (1 = Training data; 2 = Perception test data; 3 = Imagery test data |
| Run            | 1 = Run number                                                                    |
| Label          | 1 = Label (image ID)                                                              |
| VoxelData      | 1 = Voxel data                                                                    |
| voxel_x        | Voxel x coordinate                                                                |
| voxel_y        | Voxel y coordinate                                                                |
| voxel_z        | Voxel z coordinate                                                                |
| VolInds        | 1 = Volume index                                      

In [54]:
data.select('category_index')

array([[ 41.],
       [ 18.],
       [127.],
       ...,
       [  4.],
       [ 42.],
       [ 24.]])

In [49]:
train_indexes = dt == 1
test_indexes = dt == 2
fmri_data = np.array(data.select('ROI*'))
train_data = fmri_data[train_indexes[:, 0], :]
test_data = fmri_data[test_indexes[:, 0], :]

In [58]:
np.array(data.select('Label'))

array([[2.76653402e+06, 4.10000000e+01, 3.24000000e+02],
       [1.97016403e+06, 1.80000000e+01, 1.34000000e+02],
       [4.37687601e+06, 1.27000000e+02, 1.01100000e+03],
       ...,
       [1.84633102e+06, 4.00000000e+00, 4.00000000e+00],
       [4.21012001e+06, 4.20000000e+01, 4.20000000e+01],
       [3.12229503e+06, 2.40000000e+01, 2.40000000e+01]])

In [60]:
train_ids = np.array(data.select('Label'))[:, 0]
train_ids = train_ids[train_indexes[:, 0]]
train_ids.shape

(1200,)

In [62]:
import pandas as pd 
img_ids = pd.read_csv('./image_training_id.csv', header=None)

0                     1
0     1.518878e+06  n01518878_10042.JPEG
1     1.518878e+06  n01518878_12028.JPEG
2     1.518878e+06  n01518878_14075.JPEG
3     1.518878e+06  n01518878_14910.JPEG
4     1.518878e+06   n01518878_5958.JPEG
...            ...                   ...
1195  1.311188e+07  n13111881_28475.JPEG
1196  1.311188e+07   n13111881_6054.JPEG
1197  1.311188e+07   n13111881_6560.JPEG
1198  1.311188e+07   n13111881_7817.JPEG
1199  1.311188e+07   n13111881_9170.JPEG

[1200 rows x 2 columns]

In [64]:
img_ids[img_ids[0] == train_ids[10]]

0                     1
176  2.090827e+06  n02090827_10084.JPEG

In [51]:
test_data.shape

(1750, 4466)

In [40]:
dt = np.array(data.select('DataType'))
dt[dt == 2].shape

(1750,)

In [6]:
voxel_x = data.get_metadata('voxel_x', where='VoxelData')

In [29]:
vols = data.get_metadata('VolInds', where='VoxelData')

array([nan, nan, nan, ..., nan, nan, nan])

In [33]:
run = np.array(data.select('Run'))
run[run == 5].shape

(125,)

In [25]:
voxel_x.shape

(4466,)

In [18]:
labels = data.get_metadata('Label', where='VoxelData')

In [26]:
np.array(data.select('ROI_V1')).shape

(3450, 1004)

In [27]:
np.array(data.select('Label')).shape


(3450, 3)

In [96]:
[img_ids.set_index(0, drop=True).index.get_loc(train_ids[i]) for i in range(4)]


# img_ids

[323, 133, 1010, 933]